AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'script/**/*'

Style/BlockDelimiters:
  Enabled: false

Style/SpaceBeforeBlockBraces: 
  Enabled: false

Style/SpaceInsideBlockBraces: 
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/MethodLength:
  Max: 15
