require: rubocop-rspec

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'script/**/*'

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\#.*'] # ignore long comments

Style/BlockDelimiters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/MultilineBlockChain:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/ImplicitSubject:
  Enabled: false

RSpec/EmptyExampleGroup:
  CustomIncludeMethods: [its_call, its_map]

RSpec/FilePath:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
