AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'script/**/*'

Metrics/LineLength:
  Max: 100

Style/BlockDelimiters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/MultilineBlockChain:
  Enabled: false

Metrics/MethodLength:
  Max: 15
